INSERT INTO locations (name)
VALUES ('Dublin, IE'),
('Paris, FR'),
('Venice, IT'),
('Rome, IT'),
('Amsterdam, NL'),
('Tokyo, JP'),
('Kyoto, JP'),
('North Cape, NO'),
('Aspen, US'),
('New Orleans, US'),
('Sydney, AU'),
('Maldives, MV'),
('Cape Town, ZA'),
('Dubai, AE'),
('New York City, US'),
('Dubrovnik, HR'),
('Edinburgh, GB'),
('Lyon, FR'),
('Nice, FR'),
('Bordeaux, FR'),
('Strasbourg, FR'),
('Sapporo, JP'),
('Osaka, JP'),
('Kobe, JP'),
('Avignon, FR'),
('Versailles, FR'),
('Marseille, FR'),
('Carcassonne, FR'),
('Amiens, FR'),
('Toulouse, FR'),
('Cannes, FR'),
('Angers, FR'),
('Arles, FR'),
('Rotterdam, NL'),
('Maastricht, NL'),
('Warsaw, PL'),
('Vancouver, CA'),
('Niagara Falls, CA'),
('Toronto, CA'),
('Montreal, CA'),
('Quebec City, CA'),
('Banff, CA'),
('Ottawa, CA'),
('Edmonton, CA'),
('Calgary, CA'),
('Winnipeg, CA'),
('Hamilton, CA'),
('Kingston, CA'),
('London, CA'),
('California, US'),
('Texas, US'),
('Florida, US'),
('Alaska, US'),
('Hawaii, US'),
('Utah, US'),
('New Mexico, US'),
('Arizona, US'),
('Nevada, US'),
('Salt Lake City, US'),
('San Francisco, US'),
('Washington, US'),
('Washington, US'),
('Chicago, US'),
('Philadelphia, US'),
('Los Angeles, US'),
('Boston, US'),
('Miami, US'),
('Portland, US'),
('Atlanta, US'),
('Seattle, US'),
('Las Vegas, US'),
('Nashville, US'),
('Austin, US'),
('San Diego, US'),
('Long Beach, US'),
('Orlando, US'),
('Tampa, US'),
('Miami, US'),
('Baltimore, US'),
('Pittsburgh, US'),
('Charleston, US'),
('Houston, US'),
('Monterey, US'),
('Atlantic City, US'),
('Detroit, US'),
('Cleveland, US'),
('Dallas, US'),
('Denver, US'),
('Niagara Falls, US'),
('Sacramento, US'),
('St. Louis, US'),
('Walt Disney World, US'),
('Honolulu, US'),
('Salt Lake City, US'),
('Cincinnati, US'),
('Minneapolis, US'),
('Memphis, US'),
('Santa Fe, US'),
('Rochester, US'),
('Indianapolis, US'),
('Lisbon, PT'),
('Porto, PT'),
('Sintra, PT'),
('Funchal, PT'),
('Coimbra, PT'),
('Saint Petersburg, RU'),
('Moscow, RU'),
('Kaliningrad, RU'),
('Veliky Novgorod, RU'),
('Kronstadt, RU'),
('Novosibirsk, RU'),
('Pskov, RU'),
('Kuala Lumpur, MY'),
('Penang, MY'),
('Kota Kinabalu, MY'),
('Kuching, MY'),
('Johor Bahru, MY'),
('Malacca City, MY'),
('Malacca, MY'),
('Putrajaya, MY'),
('Langkawi, MY'),
('Ipoh, MY'),
('Hong Kong, HK'),
('Shanghai, CN'),
('Beijing, CN'),
('Macau, MO'),
('Lhasa, CN'),
('Nanjing, CN'),
('Shenzhen, CN'),
('Guangzhou, CN'),
('Kowloon, HK'),
('Suzhou, CN'),
('Wuhan, CN'),
('Dalian, CN'),
('Xi’an, CN'),
('Qufu, CN'),
('Hangzhou, CN'),
('Xiamen, CN'),
('Harbin, CN'),
('Qingdao, CN'),
('Chengdu, CN'),
('Shenyang, CN'),
('Kunming, CN'),
('Guilin, CN'),
('Changsha, CN'),
('Ningbo, CN'),
('Tianjin, CN'),
('Zhengzhou, CN'),
('Kashgar, CN'),
('Jinan, CN'),
('Pingyao, CN'),
('Datong, CN'),
('Yangzhou, CN'),
('Lanzhou, CN'),
('Sha Tin, HK'),
('Zhuhai, CN'),
('Haikou, CN'),
('Sanya, CN'),
('Taiyuan, CN'),
('Lijiang, CN'),
('Dengfeng, CN'),
('Jiaxing, CN'),
('Quanzhou, CN'),
('Fuzhou, CN'),
('Athens, GR'),
('Thessaloniki, GR'),
('Corfu, GR'),
('Heraklion, GR'),
('Rhodes, GR'),
('Corfu, GR'),
('Delphi, GR'),
('Santorini, GR'),
('Rethymno, GR'),
('Nafplio, GR'),
('Piraeus, GR'),
('Patras, GR'),
('Lindos, GR'),
('Rhodes, GR'),
('Cephalonia, GR'),
('Chania, GR'),
('Ioannina, GR'),
('Mykonos, GR'),
('Mytilene, GR'),
('Chios, GR'),
('Patmos, GR'),
('Epidaurus, GR'),
('Samos, GR'),
('Naxos, GR'),
('Vienna, AT'),
('Salzburg, AT'),
('Innsbruck, AT'),
('Graz, AT'),
('Linz, AT'),
('Klagenfurt, AT'),
('Hallstatt, AT'),
('Bregenz, AT'),
('Shinjuku, JP'),
('Nagoya, JP'),
('Chiyoda, JP'),
('Minato, JP'),
('Nara, JP'),
('Hiroshima, JP'),
('Nagasaki, JP'),
('Kamakura, JP'),
('Yokohama, JP'),
('Hakone, JP'),
('Kanazawa, JP'),
('Fukuoka, JP'),
('Hakodate, JP'),
('Nagano, JP'),
('Naha, JP'),
('Okayama, JP'),
('Toshima, JP'),
('Kumamoto, JP'),
('Odawara, JP'),
('Himeji, JP'),
('Bonin Islands, JP'),
('Shimonoseki, JP'),
('Sendai, JP'),
('Meguro, JP'),
('Asahikawa, JP'),
('Otaru, JP'),
('Biei, JP'),
('Hakodate, JP'),
('London, GB'),
('Manchester, GB'),
('York, GB'),
('Bath, GB'),
('Birmingham, GB'),
('Brighton, GB'),
('Leeds, GB'),
('Newcastle, GB'),
('Glasgow, GB'),
('Liverpool, GB'),
('Oxford, GB'),
('Cardiff, GB'),
('City of London, GB'),
('Blackpool, GB'),
('Belfast, GB'),
('Bristol, GB'),
('Cambridge, GB'),
('Portsmouth, GB'),
('Stratford-upon-Avon, GB'),
('Norwich, GB'),
('Plymouth, GB'),
('Aberdeen, GB'),
('Exeter, GB'),
('Canterbury, GB'),
('Dundee, GB'),
('Sheffield, GB'),
('Chester, GB'),
('Bournemouth, GB'),
('Shrewsbury, GB'),
('Whitby, GB'),
('Leicester, GB'),
('Salisbury, GB'),
('Southampton, GB'),
('Eastbourne, GB'),
('Nottingham, GB'),
('Coventry, GB'),
('Warwick, GB'),
('Bangkok, TH'),
('Ko Tao, TH'),
('Chiang Mai, TH'),
('Pattaya, TH'),
('Ko Samui, TH'),
('Patong, TH'),
('Chiang Rai, TH'),
('Ko Pha-ngan, TH'),
('Ao Nang, TH'),
('Khao Lak, TH'),
('Kanchanaburi, TH'),
('Phuket, TH'),
('Ko Phi Phi, TH'),
('Nakhon Pathom, TH'),
('Hat Yai, TH'),
('Berlin, DE'),
('Hamburg, DE'),
('Munich, DE'),
('Frankfurt, DE'),
('Düsseldorf, DE'),
('Cologne, DE'),
('Dresden, DE'),
('Stuttgart, DE'),
('Koblenz, DE'),
('Bamberg, DE'),
('Potsdam, DE'),
('Füssen, DE'),
('Nuremberg, DE'),
('Trier, DE'),
('Regensburg, DE'),
('Leipzig, DE'),
('Stralsund, DE'),
('Wiesbaden, DE'),
('Essen, DE'),
('Weimar, DE'),
('Lübeck, DE'),
('Heidelberg, DE'),
('Bochum, DE'),
('Dortmund, DE'),
('Aachen, DE'),
('Schwerin, DE'),
('Augsburg, DE'),
('Hanover, DE'),
('Goslar, DE'),
('Rostock, DE'),
('Würzburg, DE'),
('Erfurt, DE'),
('Mexico City, MX'),
('Cozumel, MX'),
('Chichen Itza, MX'),
('Playa del Carmen, MX'),
('Puerto Vallarta, MX'),
('Cabo San Lucas, MX'),
('Palenque, MX'),
('San Miguel de Allende, MX'),
('Guadalajara, MX'),
('Oaxaca City, MX'),
('Cancún, MX'),
('Guanajuato City, MX'),
('Teotihuacan, MX'),
('Querétaro City, MX'),
('Istanbul, TR'),
('Antalya, TR'),
('Alanya, TR'),
('Bursa, TR'),
('Bodrum, TR'),
('Pamukkale, TR'),
('Ankara, TR'),
('Edirne, TR'),
('Adana, TR'),
('Trabzon, TR'),
('Konya, TR'),
('Florence, IT'),
('Milan, IT'),
('Siena, IT'),
('Verona, IT'),
('Naples, IT'),
('Catania, IT'),
('Syracuse, IT'),
('Turin, IT'),
('Genoa, IT'),
('Trieste, IT'),
('Pompeii, IT'),
('Pisa, IT'),
('Ferrara, IT'),
('Ravenna, IT'),
('Sicily, IT'),
('Tuscany, IT'),
('Veneto, IT'),
('Sardinia, IT'),
('Capri, IT'),
('Cinque Terre, IT'),
('Andalusia, ES'),
('Catalonia, ES'),
('Canary Islands, ES'),
('Barcelona, ES'),
('Madrid, ES'),
('Seville, ES'),
('Málaga, ES'),
('Granada, ES'),
('Valencia, ES'),
('Toledo, ES'),
('Bilbao, ES'),
('Puerto de la Cruz, ES'),
('Santa Cruz de Tenerife, ES'),
('Las Palmas, ES'),
('Girona, ES'),
('Salou, ES'),
('Tarragona, ES'),
('Borobudur, ID'),
('Ubud, ID'),
('Jakarta, ID'),
('Prambanan, ID'),
('Bandung, ID'),
('Kuta, ID'),
('Yogyakarta, ID'),
('Nusa Lembongan, ID'),
('Bogor, ID'),
('Bali, ID'),
('Nusa Dua, ID'),
('Jimbaran, ID'),
('Medan, ID'),
('Denpasar, ID'),
('Surabaya, ID'),
('Jeju, KR'),
('Seoul, KR'),
('Busan, KR'),
('Gyeongju, KR'),
('Geneva, CH'),
('Zürich, CH'),
('Basel, CH'),
('Zermatt, CH'),
('Bern, CH'),
('Lausanne, CH'),
('Lucerne, CH'),
('Lugano, CH'),
('Split, HR'),
('Zagreb, HR'),
('Pula, HR'),
('Zadar, HR'),
('Trogir, HR'),
('Johannesburg, ZA'),
('Pretoria, ZA'),
('Durban, ZA'),
('Stellenbosch, ZA'),
('Knysna, ZA'),
('Budapest, HU'),
('Pécs, HU'),
('Szeged, HU'),
('Eger, HU'),
('Sharm El Sheikh, EG'),
('Hurghada, EG'),
('Luxor, EG'),
('Cairo, EG'),
('Dahab, EG'),
('Alexandria, EG'),
('Aswan, EG'),
('Giza, EG'),
('Marrakesh, MA'),
('Essaouira, MA'),
('Rabat, MA'),
('Casablanca, MA'),
('Galway, IE'),
('Limerick, IE'),
('Kilkenny, IE'),
('Killarney, IE'),
('Jaipur, IN'),
('New Delhi, IN'),
('Mamallapuram, IN'),
('Mumbai, IN'),
('Kolkata, IN'),
('Udaipur, IN'),
('Agra, IN'),
('Hampi, IN'),
('Mysore, IN'),
('Amritsar, IN'),
('Fatehpur Sikri, IN'),
('Varanasi, IN'),
('Bangalore, IN'),
('Luxembourg, LU'),
('Vianden, LU'),
('Echternach, LU'),
('Melbourne, AU'),
('Perth, AU'),
('Hobart, AU'),
('Brisbane, AU'),
('Canberra, AU'),
('Cairns, AU'),
('Adelaide, AU'),
('Wellington, NZ'),
('Auckland, NZ'),
('Queenstown, NZ'),
('Christchurch, NZ'),
('Rotorua, NZ'),
('São Paulo, BR'),
('Rio de Janeiro, BR'),
('Salvador, BR'),
('Curitiba, BR'),
('Oslo, NO'),
('Bergen, NO'),
('Trondheim, NO'),
('Stavanger, NO'),
('Kristiansand, NO'),
('Helsinki, FI'),
('Tampere, FI'),
('Turku, FI'),
('Ho Chi Minh, VN'),
('Hanoi, VN'),
('Da Nang, VN'),
('Da Lat, VN'),
('Siem Reap, KH'),
('Phnom Penh, KH'),
('Angkor, KH'),
('Singapore, SG'),
('Fiji, FJ'),
('Stockholm, SE'),
('Malmö, SE'),
('Gothenburg, SE'),
('Karlskrona, SE'),
('Visby, SE'),
('Uppsala, SE'),
('Lund, SE'),
('Amalfi, IT'),
('Amalfi Coast, IT'),
('Abu Dhabi, AE'),
('Oman, OM'),
('Muscat, OM'),
('Khasab, OM'),
('Saudi Arabia, SA'),
('Mecca, SA'),
('Jeddah, SA'),
('Medina, SA'),
('Qatar, QA'),
('Doha, QA'),
('Zubarah, QA'),
('Bahrain, BH'),
('Manama, BH'),
('Muharraq, BH'),
('Israel, IL'),
('Jerusalem, IL'),
('Tel Aviv, IL'),
('Nazareth, IL'),
('Jaffa, IL'),
('Eilat, IL'),
('Haifa, IL'),
('Istanbul, TR'),
('Jordan, JO'),
('Petra, JO'),
('Amman, JO'),
('Afghanistan, AF'),
('Kabul, AF'),
('Herat, AF'),
('Iran, IR'),
('Persepolis, IR'),
('Tehran, IR'),
('Shiraz, IR'),
('Iraq, IQ'),
('Babylon, IQ'),
('Baghdad, IQ'),
('Lebanon, LB'),
('Beirut, LB'),
('Bellevue, US')
;
